routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\BotController;
use App\Http\Controllers\CKEditorController;
use App\Http\Controllers\CustomLoginController;
use App\Http\Controllers\ForecastsController;
use App\Http\Controllers\FreeKassaController;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\SeamlessLoginController;
use App\Http\Controllers\TariffController;
use App\Http\Controllers\TheoriesController;
use App\Http\Middleware\AdminMiddleware;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
// Route::get('/admin', [AdminController::class, 'index']);

// Route::get('login', [LoginController::class, 'authenticate'])->name('authenticate');
// Route::post('login', [LoginController::class, 'authenticate'])->name('authenticate');

Route::get('test', function () {
    echo phpinfo();
});

// Route::any('/bot/receive', [BotController::class, 'receiveMessage'])->name('receiveMessage');
Route::any('/bot/receive', [BotController::class, 'sendMessage'])->name('sendMessage');


Route::get('/', [App\Http\Controllers\PagesController::class, 'index'])->name('home');

Route::group(['middleware' => ['auth', 'admin']], function () {



    Route::post('ckeditor/image-upload', [CKEditorController::class, 'uploadImage'])->name('ckeditor.image-upload');
    Route::post('ckeditor/upload', [CKEditorController::class, 'upload'])->name('ckeditor.upload');

    Route::get('/admin/theory/create', [TheoriesController::class, 'createTheory'])->name('addtheory');
    Route::post('/admin/theory/create', [TheoriesController::class, 'storeTheory'])->name('storeTheory');
    Route::get('/admin/theory/all', [TheoriesController::class, 'allTheories'])->name('alltheories');
    Route::get('/admin/theory/edit/{theory}', [TheoriesController::class, 'editTheory'])->name('editTheory');
    Route::post('/admin/theory/update/{theory}', [TheoriesController::class, 'updateTheory'])->name('updatetheory');
    Route::post('/admin/theory/{theory}', [TheoriesController::class, 'deleteTheory'])->name('deleteTheory');
    Route::post('/admin/ajax/user/{user}', [AdminController::class, 'deleteUser'])->name('deleteUser');

    Route::get('admin', [AdminController::class, 'index'])->name('admin');
    Route::get('/admin/users', [AdminController::class, 'users'])->name('users');
    Route::get('/admin/messages', [AdminController::class, 'allMessages'])->name('messages');
    Route::get('/admin/widgets', [AdminController::class, 'allWidgets'])->name('widgets');

    Route::get('/admin/payments/{payment}', [AccountController::class, 'editPayment'])->name('editPayment');
    Route::post('/admin/payments/{payment}', [AccountController::class, 'updatePayment'])->name('updatePayment');

    Route::get('/admin/forecast/add', [ForecastsController::class, 'addForecast'])->name('addforecast');
    Route::post('/admin/forecast/add', [ForecastsController::class, 'storeForecast'])->name('addforecast');
    Route::get('/admin/forecast/all', [ForecastsController::class, 'allForecasts'])->name('allforecasts');
    Route::get('/admin/forecast/delete/{forecast}', [ForecastsController::class, 'deleteForecast'])->name('deleteForecast');
    Route::post('/admin/forecast/update/{forecast}', [ForecastsController::class, 'updateForecast'])->name('updateForecast');

    Route::get('/admin/forecast/edit/{forecast}', [ForecastsController::class, 'editForecast'])->name('editForecast');
    Route::get('/admin/forecastResult/{forecast}', [ForecastsController::class, 'editForecastResult'])->name('editForecastResult');



    Route::get('/admin/forecastResults', [ForecastsController::class, 'allForecastResult'])->name('allForecastResult');
    Route::get('/admin/forecastResult/{forecast}', [ForecastsController::class, 'addForecastResult'])->name('addForecastResult');
    Route::post('/admin/forecastResult/{forecast}/create', [ForecastsController::class, 'storeForecastResult'])->name('storeForecastResult');



    Route::get('/admin/tariff/create', [TariffController::class, 'createTariff'])->name('addtariff');
    Route::post('/admin/tariff/create', [TariffController::class, 'storeTariff'])->name('addtariff');
    Route::get('/admin/tariff/all', [TariffController::class, 'allTariffs'])->name('alltariffs');
    Route::get('/admin/tariff/edit/{tariff}', [TariffController::class, 'editTariff'])->name('edittariff');
    Route::post('/admin/tariff/update/{tariff}', [TariffController::class, 'updateTariff'])->name('updatetariff');
    Route::get('/admin/tariff/delete/{tariff}', [TariffController::class, 'deleteTariff'])->name('deleteTariff');

    Route::get('/admin/withdrawals', [AccountController::class, 'withdrawals'])->name('allWithdrawals');
    Route::get('/admin/payments', [AccountController::class, 'allPayments'])->name('allPayments');

    Route::post('/admin/ajax/update_payment/{payment}', [AccountController::class, 'updatePayment'])->name('updatePayment');
    Route::post('/admin/ajax/update_withdrawal/{withdrawal}', [AccountController::class, 'updateWithdrawal'])->name('updateWithdrawal');
    Route::post('/admin/ajax/update_widget/{widget}', [AdminController::class, 'updateWidget'])->name('updateWidget');

    Route::get('/admin/{controller}', [TariffController::class, 'index']);

});
Route::group(['middleware' => ['auth']], function () {
    // profile vs user operations
    Route::get('/affiliate', [App\Http\Controllers\ProfileController::class, 'affiliate'])->name('affiliate');
    Route::post('/cabinet', [App\Http\Controllers\ProfileController::class, 'store'])->name('store'); // saving submitted data
    Route::get('cabinet', [App\Http\Controllers\ProfileController::class, 'edit'])->name('cabinet'); // editing cabinet form
    Route::get('/notifications', [App\Http\Controllers\ProfileController::class, 'notifications'])->name('notifications');

    Route::get('/referals', [App\Http\Controllers\ProfileController::class, 'referals'])->name('referals');
    Route::get('/withdrawal', [App\Http\Controllers\AccountController::class, 'withdrawal'])->name('withdrawal');
    Route::post('/withdrawal', [App\Http\Controllers\AccountController::class, 'withdrawalStore'])->name('withdrawalStore');


    // account controller operations
    Route::post('/addup', [App\Http\Controllers\AccountController::class, 'storePayment'])->name('storePayment'); // accepting payment storing
    Route::get('/payment/{public_id}', [App\Http\Controllers\PagesController::class, 'checkPayment'])->name('checkPayment');
    Route::get('/payments', [App\Http\Controllers\AccountController::class, 'payments'])->name('payments');
    Route::get('/addup', [App\Http\Controllers\AccountController::class, 'addup'])->name('addup'); // accepting payment form

    Route::post('/addup/{payment}', [App\Http\Controllers\AccountController::class, 'fillup'])->name('fillup'); // accepting payment for purchase

});



Route::get('/history', [PagesController::class, 'history'])->name('history');
Route::get('/stats', [PagesController::class, 'stats'])->name('stats');

Route::get('/contact', [PagesController::class, 'contact']);
Route::post('/contact', [PagesController::class, 'storeMessage']);

Route::get('forecasts/free', [PagesController::class, 'free'])->name('forecasts.free');
Route::get('forecasts/paid', [PagesController::class, 'paid']);
Route::get('purchased', [PagesController::class, 'purchased'])->name('purchased');

Route::get('tariffs', [PagesController::class, 'tariffs'])->name('tariffs');

Route::get('tariffs/{id}', [PagesController::class, 'makePayment'])->name('makePayment');


Route::post('/paybill', [App\Http\Controllers\AccountController::class, 'payBill'])->name('paybill'); // accepting payment from forecasts/paid/{id}
Route::get('/checkpayment/{purchase}', [App\Http\Controllers\AccountController::class, 'checkPayment'])->name('checkpayment'); // accepting payment from forecasts/paid/{id}

Route::get('/payment/pay/{payment}', [App\Http\Controllers\AccountController::class, 'payPayment'])->name('paypayment'); // accepting payment from forecasts/paid/{id}



Route::resource('forecasts', ForecastsController::class);
Route::get('/theories/free', [TheoriesController::class, 'free'])->name('theories.free');
Route::get('/theories/paid', [TheoriesController::class, 'paid'])->name('theories.paid');
Route::resource('theories', TheoriesController::class);
Route::get('login/{type}', [CustomLoginController::class, 'index']);


Route::get('auth', [SeamlessLoginController::class, 'index']);

Auth::routes(['verify' => true]);
Auth::routes();

Route::get('/freekassa/result', [ FreeKassaController::class, 'handlePayment']);
Route::get('/freekassa/success', [ FreeKassaController::class, 'paidOrder']);
Route::get('/freekassa/fail', [ FreeKassaController::class, 'unpaidOrder']);



Route::get('/clear', function() {

    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    Artisan::call('view:clear');

    return "Cleared!";

 });

resources/views/pages/affiliate.blade.php
{{-- {{ddd($currentUser)}} --}}
@extends('layouts.app')

@section('content')

    <div class="container profile_page mt-4">
        <div class="row">
            @include('../includes/cabinet-menu')
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h4>Pul ishlamoqchisiz? men siz uchun imkon beraman!</h4>
                                <hr>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">

                                Pul ishlash uchun sizdan, pul ishlashga qiziquvchi do'stlaringizni pastdagi <strong>maxsus manzil</strong> orqali taklif qiling va ular men tavsiya qiladigan prognozlarni yoki tariflarni sotib olsa, sizning hisobingizga
                                <strong>{{ env('AFFILIATE_PERCENT', 20) }}%</strong> summa yoziladi.
                                <br>
                                Bu pulni chiqarib olish uchun pul chiqarishga buyurtmani adminga yuborasiz, Pul chiqarishga berilgan buyurtmangiz summasi joyiga tashlab beriladi.
                                <br/>
                                <strong>Ish kunlari:</strong> Dushanba-Juma gacha.
                                <hr/>
                                <strong>Sizning maxsus manzilingiz:</strong>
                                <div class="input-group mb-3">
                                    <input disabled type="text" id="referalLink" class="form-control" value="{{Config::get('app.url')}}/register?referer={{$currentUser->username}}" aria-label="Recipient's username" aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-outline-secondary" onclick="copyToClipboard()" type="button">Nusxalash</button>
                                    </div>
                                </div>

                                <script>
                                    function copyToClipboard() {
                                    /* Get the text field */
                                        var copyText = document.getElementById("referalLink");

                                        /* Select the text field */
                                        copyText.select();
                                        copyText.setSelectionRange(0, 99999); /*For mobile devices*/

                                        /* Copy the text inside the text field */
                                        document.execCommand("copy");

                                        /* Alert the copied text */
                                        alert("Buferga yozildi: " + copyText.value);
                                    }
                                </script>

                                <div class="text-danger ">Endi buferga olingan manzilni do'stlaringizga jo'nating!</div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/pages/cabinet.blade.php
@extends('layouts.app')

@section('content')

    <div class="container profile_page mt-4">
        <div class="row">

            @include('../includes/cabinet-profile')
            @include('../includes/cabinet-menu')
            <div class="col-md-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h4>Sizning profilingiz ma'lumotlari</h4>
                                <hr>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <form method="POST" enctype="multipart/form-data" action="/cabinet">

                                @csrf
                                <div class="form-group row">
                                    <label for="username" class="col-lg-4 col-sm-12 col-form-label " >Nikingiz</label>
                                    <div class="col-lg-8 col-sm-12">
                                        <input id="username" value="{{$user->username}}" name="username" disabled placeholder="Username" class="form-control here" required="required" type="text">
                                    </div>
                                    @error('username')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                                <div class="form-group row">
                                    <label for="email" class="col-lg-4 col-sm-12  col-form-label">Email</label>
                                    <div class="col-lg-8 col-sm-12">
                                        <input class="form-control" id="email" name="email" value="{{$user->email}}" disabled placeholder="Email" class="form-control here" required="required" type="text">
                                    </div>
                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>

                                <div class="form-group row">
                                    <label for="first_name" class="col-lg-4 col-sm-12 col-form-label">Ismingiz:</label>
                                    <div class="col-lg-8 col-sm-12">
                                        <input id="first_name" value="{{$user->profile->first_name}}" name="first_name" placeholder="Kiriting..." class="form-control here" type="text">
                                    </div>
                                    @error('first_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group row">
                                    <label for="last_name" class="col-lg-4 col-sm-12 col-form-label">Familiyangiz:</label>
                                    <div class="col-lg-8 col-sm-12">
                                        <input id="last_name" value="{{$user->profile->last_name}}" name="last_name" placeholder="Kiriting..." class="form-control here" type="text">
                                    </div>

                                    @error('last_name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group row">
                                    <label for="url" class="col-lg-4 col-sm-12 col-form-label">Vebsayt</label>
                                    <div class="col-lg-8 col-sm-12">
                                        <input id="url" value="{{$user->profile->url}}" name="url" placeholder="url" class="form-control here" type="url">
                                    </div>

                                    @error('url')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group row">
                                    <label for="website" class="col-lg-4 col-sm-12 col-form-label">Rasmingiz</label>
                                    <div class="col-lg-8 col-sm-12">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input @error('image') is-invalid @enderror"
                                                   id="image" name="image"
                                                   value="{{ old('image') }}"
                                                   autocomplete="image">
                                            <label class="custom-file-label" for="image">Choose file</label>
                                            @error('image')
                                                <span class="invalid-feedback" role="alert">
                                                    <strong>{{ $message }}</strong>
                                                </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                                <hr>
                                <div class="form-group row">
                                    <label for="url" class="col-lg-4 col-sm-12 col-form-label">YooMoney (Яндекс.Деньги) </label>
                                    <div class="col-lg-8 col-sm-12">
                                        <input id="yandex_money" value="{{$user->account->yandex_money}}" name="yandex_money" placeholder="koshelok raqamingiz" class="form-control here" type="text">
                                    </div>

                                    @error('url')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group row">
                                    <label for="url" class="col-lg-4 col-sm-12 col-form-label">Qiwi </label>
                                    <div class="col-lg-8 col-sm-12">
                                        <input id="qiwi" value="{{$user->account->qiwi}}" name="qiwi" placeholder="koshelok raqamingiz" class="form-control here" type="text">
                                    </div>

                                    @error('url')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                                <div class="form-group row">
                                    <div class="col-lg-8 col-sm-12 offset-lg-4">
                                    <button name="submit" type="submit" class="btn btn-block btn-primary">Profil ni yangilash</button>
                                    </div>
                                </div>
                                </form>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/pages/tariffs.blade.php
@extends('layouts.app')

@section('content')


<!-- content -->

<div class="timer_forecasts mt-2">
    <div class="new_forecasts_table" id="timerForecasts">
      <a class="font-weight-bold bg-primary text-white">
          <div class="date_td">Vaqti</div>
          <div>Stavka turi</div>
          <div>Chempionat</div>
          <div>Jamoalar</div>
          <div>Kupon kod</div>
          <div class="rate">KF</div>
          {{-- <div class="datetime">{{date("M d, Y H:i:s", strtotime($item->begin))}}</div> --}}
          <div>Taymer</div>
      </a>
      @forelse($timerForecasts as $item)
      <a href="{{route('forecasts.show', $item->link)}}">
              <div class="date_td">{{date("m.d, H:i", strtotime($item->begin))}}</div>
              <div>{{$item->sport_type}}</div>
              <div>{{$item->chempionat}}</div>
              <div>{{$item->first_team}} - {{$item->second_team}}</div>
              <div>{{$item->forecast_value}}</div>
              <div class="rate">{{$item->kf}}</div>
              {{-- <div class="datetime">{{date("M d, Y H:i:s", strtotime($item->begin))}}</div> --}}
              <div class="timer " data-datetime="{{date("M d, Y H:i:s", strtotime($item->begin))}}">
                    <span class="days"></span>
                    <span class="time">13:04:49</span>
                </div>
      </a>
      @empty
      Prognozlar hali chiqarilmagan!
      @endforelse


    </div>
    <p class="hint"><a href="/history/">Barcha prognozlar</a></p>
</div>


<div class="paid__section mt-2">
    <div class="section_header">
      <div class="">
        <h3 class="paid__title">
          <mark>Prognozlarni</mark> sotib olish
        </h3>
        <p class="paid__title_description text-center">
          Donali yoki muddatli tarifflarni tanlang.
        </p>
      </div>
      <div class="section_right switcher">
        <div class="forecast__switcher">
          {{-- <a href="#" class="forecast_type bet_of_day ">Kun stavkasi</a> --}}
          <a href="#" class="forecast_type active">Beton stavkalar</a>
        </div>
      </div>
    </div>


    <div class="row paid__items">
        @if (count($tariffs->pieces) > 0)
        @foreach ($tariffs->pieces as $tariff)
            @if ($tariff->type !== 'term')
            @if ($tariff->discount > 0)
            <div class="col-md-3 w-md-50 paid__items_i stavka_dnya with_discount displayed">
                <div class="discount">
                    Skidka <span class="discount_percentage">{{$tariff->discount}}%</span>
                </div>
            @else
                <div class="col-md-3 paid__items_i stavka_dnya displayed ">
            @endif

                <h4 class="item_header " styl="font-size: 1.1em !important;">

                        {{$tariff->quantity}}

                    ta prognoz</h4>
                <div class="item_content">
                <h3 class="item_price " style="font-size: 1.5em;">
                    @if ($tariff->discount != 0 && $tariff->discount != null)
                        <span class="actual_price">{{$tariff->price}} so'm.</span>
                        {{$tariff->price - $tariff->discount/100 * $tariff->price}} so'm
                    @else
                    {{$tariff->price}} so'm
                    @endif
                </h3>
                <ul class="list item_advantages">
                    <li class="list_item">Yutuq extimoli 75%</li>
                    <li class="list_item">O'rtacha koeffitsient 3</li>
                    <li class="list_item">Har kunlik rejim</li>
                    <li class="list_item">Yutish sirlari o'rgatiladi</li>
                    <li class="list_item">Stavka yutqazilganda bepul beriladi</li>
                </ul>

                <a href="/tariffs/{{$tariff->id}}" class="item_buy_btn">
                    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                    </svg>
                    Sotib olish
                </a>
                </div>
            </div>
            @endif
        @endforeach
        @else
            Hali tariflar qo'shilmagan.
        @endif
    </div>

    <div class="row mt-4 forecasts_by_period displayed">
        <div class="item_banner">
            <img src="/imgs/telegram-lg-icon.png" alt="Telegram Kanal" class="telegram_lg_icon">
          <h3 class="item_title">Hoziroq <a href="https://t.me/infojahon_uz"><mark>Telegramdagi</mark></a>vip kanalimga ulaning</h3>

            <p class="item_description">
              Har kunlik Liniya ,live va ordinar stavkalar. 2+ Expreslar.Bankni to'g'ri taqsimlash va yutish sirlari o'rgatiladi
            </p>

            <div class="item_stats">
              <div class="stats_bank border border-primary">
                <span class="">
                  Oxrigi haftada berilgan prognozlarni o'tish foizi
                </span>
                <span class="yellow_text" style="font-size: 1.5em;">{{sprintf("%.1f", $statDetails['last_weeks_wins_percentage'] ?? 0)}}%</span>
              </div>
              <div class="stats_bets border border-primary">
                <span class="">
                  Oxrigi haftada berilgan prognozlar soni
                </span>
                <span class="yellow_text" style="font-size: 1.5em;"> {{$statDetails['last_weeks_all']}} ta</span>
              </div>
            </div>

        </div>

        <div class="forecasts_by_period__items displayed">
            @foreach ($tariffs->terms as $tariff)
                @if ($tariff->type == 'term')
                    @if ($tariff->discount != 0)
                        <div class="forecasts_by_period__items_i mt-2">

                            <span class="item_discount_percent">
                                <mark>-{{$tariff->discount}}%</mark>
                            </span>
                            <h6 class="item_period">{{$tariff->term}} kunlik Vip </h6>

                            <h5 class="item_price">
                            @if ($tariff->discount != 0)
                                <span class="actual_price"> {{$tariff->price}} so'm.</span>
                            @endif
                            {{$tariff->price -  $tariff->discount / 100 * $tariff->price }} so'm.
                            </h5>
                            <a href="/tariffs/{{$tariff->id}}" class="item_btn">Sotib olish</a>
                        </div>
                    @else
                        <div class="forecasts_by_period__items_i">
                            <h6 class="item_period">{{$tariff->term}} kunlik Vip </h6>
                            <h5 class="item_price">

                            {{$tariff->price}} so'm.
                            </h5>
                            <a href="/tariffs/{{$tariff->id}}" class="item_btn">Sotib olish</a>
                        </div>
                    @endif
                @endif
            @endforeach

          {{-- <div class="forecasts_by_period__items_i">
            <span class="item_discount_percent">
              <mark>-30%</mark>
            </span>
            <h6 class="item_period">3 Oylik Vip</h6>
            <h5 class="item_price">
              <span class="actual_price">2.4 mln so'm.</span>
              1 mln so'm.
            </h5>
            <a href="#buy" class="item_btn">Sotib olish</a>
          </div>
          <div class="forecasts_by_period__items_i">
            <span class="item_discount_percent">
              <mark>-30%</mark>
            </span>
            <h6 class="item_period">Yillik Vip</h6>
            <h5 class="item_price">
              <span class="actual_price">10 mln so'm.</span>
              3 mln so'm.
            </h5>
            <a href="#buy" class="item_btn">Sotib olish</a>
          </div> --}}
        </div>

      </div>




  </div>

<br>
<br>
<br>

      <!-- content -->
@endsection